name = "BaryPlots"
uuid = "435fd04b-d7a1-466b-a36d-8293cbb03b07"
authors = ["aureliano <datadreamscorp@protonmail.com>"]
version = "0.1.2"
license = "MIT"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"
DifferentialEquations = "7.14"
ForwardDiff = "0.10"
NLsolve = "4.5"
Plots = "1.40"

